from ..ansitowin32 import AnsiToWin32 as AnsiToWin32, StreamWrapper as StreamWrapper
from ..win32 import ENABLE_VIRTUAL_TERMINAL_PROCESSING as ENABLE_VIRTUAL_TERMINAL_PROCESSING
from .utils import osname as osname
from unittest import TestCase

class StreamWrapperTest(TestCase):
    def testIsAProxy(self) -> None: ...
    def testDelegatesWrite(self) -> None: ...
    def testDelegatesContext(self) -> None: ...
    def testProxyNoContextManager(self) -> None: ...
    def test_closed_shouldnt_raise_on_closed_stream(self) -> None: ...
    def test_closed_shouldnt_raise_on_detached_stream(self) -> None: ...

class AnsiToWin32Test(TestCase):
    def testInit(self) -> None: ...
    def testStripIsTrueOnWindows(self) -> None: ...
    def testStripIsFalseOffWindows(self) -> None: ...
    def testWriteStripsAnsi(self) -> None: ...
    def testWriteDoesNotStripAnsi(self) -> None: ...
    def assert_autoresets(self, convert: bool, autoreset: bool = ...) -> None: ...
    def testWriteAutoresets(self) -> None: ...
    def testWriteAndConvertWritesPlainText(self) -> None: ...
    def testWriteAndConvertStripsAllValidAnsi(self) -> None: ...
    def testWriteAndConvertSkipsEmptySnippets(self) -> None: ...
    def testWriteAndConvertCallsWin32WithParamsAndCommand(self) -> None: ...
    def test_reset_all_shouldnt_raise_on_closed_orig_stdout(self) -> None: ...
    def test_wrap_shouldnt_raise_on_closed_orig_stdout(self) -> None: ...
    def test_wrap_shouldnt_raise_on_missing_closed_attr(self) -> None: ...
    def testExtractParams(self) -> None: ...
    def testCallWin32UsesLookup(self) -> None: ...
    def test_osc_codes(self) -> None: ...
    def test_native_windows_ansi(self) -> None: ...
