from ..ansi import Back as Back, Fore as Fore, Style as Style
from ..ansitowin32 import AnsiToWin32 as AnsiToWin32
from _typeshed import Incomplete
from unittest import TestCase

stdout_orig: Incomplete
stderr_orig: Incomplete

class AnsiTest(TestCase):
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def testForeAttributes(self) -> None: ...
    def testBackAttributes(self) -> None: ...
    def testStyleAttributes(self) -> None: ...
