from ..ansitowin32 import StreamWrapper as StreamWrapper
from ..initialise import init as init, just_fix_windows_console as just_fix_windows_console
from .utils import osname as osname, replace_by as replace_by
from _typeshed import Incomplete
from unittest import TestCase
from unittest.mock import Mock as Mock

orig_stdout: Incomplete
orig_stderr: Incomplete

class InitTest(TestCase):
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def assertWrapped(self) -> None: ...
    def assertNotWrapped(self) -> None: ...
    def testInitWrapsOnWindows(self, _: Mock) -> None: ...
    def testInitDoesntWrapOnEmulatedWindows(self, _: Mock) -> None: ...
    def testInitDoesntWrapOnNonWindows(self) -> None: ...
    def testInitDoesntWrapIfNone(self) -> None: ...
    def testInitAutoresetOnWrapsOnAllPlatforms(self) -> None: ...
    def testInitWrapOffDoesntWrapOnWindows(self) -> None: ...
    def testInitWrapOffIncompatibleWithAutoresetOn(self) -> None: ...
    def testAutoResetPassedOn(self, mockATW32: Mock, _: Mock) -> None: ...
    def testAutoResetChangeable(self, mockATW32: Mock) -> None: ...
    def testAtexitRegisteredOnlyOnce(self, mockRegister: Mock) -> None: ...

class JustFixWindowsConsoleTest(TestCase):
    def tearDown(self) -> None: ...
    def testJustFixWindowsConsole(self) -> None: ...
