from ..ansitowin32 import AnsiToWin32 as AnsiToWin32, StreamWrapper as StreamWrapper
from .utils import StreamNonTTY as StreamNonTTY, StreamTTY as StreamTTY, pycharm as pycharm, replace_by as replace_by, replace_original_by as replace_original_by
from unittest import TestCase

def is_a_tty(stream: StreamTTY) -> bool: ...

class IsattyTest(TestCase):
    def test_TTY(self) -> None: ...
    def test_nonTTY(self) -> None: ...
    def test_withPycharm(self) -> None: ...
    def test_withPycharmTTYOverride(self) -> None: ...
    def test_withPycharmNonTTYOverride(self) -> None: ...
    def test_withPycharmNoneOverride(self) -> None: ...
    def test_withPycharmStreamWrapped(self) -> None: ...
