from collections.abc import Generator
from io import StringIO

class StreamTTY(StringIO):
    def isatty(self) -> bool: ...

class StreamNonTTY(StringIO):
    def isatty(self) -> bool: ...

def osname(name: str) -> Generator[None, None, None]: ...
def replace_by(stream: StreamTTY) -> Generator[None, None, None]: ...
def replace_original_by(stream: StreamTTY) -> Generator[None, None, None]: ...
def pycharm() -> Generator[None, None, None]: ...
