from unittest import TestCase
from unittest.mock import Mock

class WinTermTest(TestCase):
    def testInit(self, mockWin32: Mock) -> None: ...
    def testGetAttrs(self) -> None: ...
    def testResetAll(self, mockWin32: Mock) -> None: ...
    def testFore(self) -> None: ...
    def testBack(self) -> None: ...
    def testStyle(self) -> None: ...
    def testSetConsole(self, mockWin32: Mock) -> None: ...
    def testSetConsoleOnStderr(self, mockWin32: Mock) -> None: ...
