default_language_version:
  python: python3

ci:
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit suggestions"
  autoupdate_schedule: quarterly
  # submodules: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: detect-private-key

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: ["--write-changes"]
        exclude: pyproject.toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      # try to fix what is possible
      - id: ruff
        args: ["--fix"]
      # perform formatting updates
      - id: ruff-format
      # validate if all is fine with preview mode
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        always_run: true
        pass_filenames: false

  - repo: local
    hooks:
      - id: python-safety-dependencies-check
        name: safety
        entry: safety
        args: ["check", "--full-report", "--file"]
        language: system
        files: requirements