#!/usr/bin/env bash

# Test the currently built release of Colorama from the dist/ dir.
# Run this before making a release.
#
# This should be run on Windows, because Colorama is mostly a no-op elsewhere.
# Hmmm, this script should probably be a .bat file then? Nah, WSL FTW.
#
# Uploads package from the dist/ directory to the *test* PyPI.
# Create a fresh virtualenvironment and install colorama from test PyPI.
# Import Colorama and make trivial use of it.

# Exit on error
set -eu -o pipefail

syspython=python3.8
bin="$HOME/.virtualenvs/colorama/bin"
version=$($bin/python setup.py --version)
sandbox=test-release-playground

# Upload to the test PyPI.
$bin/twine upload --repository testpypi dist/colorama-$version-* \
    || echo "  > Expect a 400 if package was already uploaded."

# cd elsewhere so we cannot import from local source.
mkdir -p $sandbox
(
    cd $sandbox

    # Create a temporary disposable virtualenv.
    $syspython -m venv --clear venv

    # Install the package we just uploaded.
    # (--extra-index-url for this project's requirements)
    venv/bin/python -m pip --quiet install --index-url https://test.pypi.org/simple --extra-index-url https://pypi.org/simple colorama==$version

    # Import and use Colorama from the temp virtualenv.
    venv/bin/python -c "import colorama; colorama.init(); print(colorama.Fore.GREEN + \"OK: Colorama\", colorama.__version__, \"from test pypi install.\")"
)

# Tidy up
rm -rf $sandbox

